# Generated by Django 2.2 on 2020-07-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUERY_SUBJECT', models.CharField(max_length=500)),
                ('QUERY_TEXT', models.CharField(max_length=500)),
                ('DATE', models.CharField(max_length=50)),
                ('TIME', models.CharField(max_length=50)),
                ('STATUS', models.CharField(max_length=25)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student_table')),
            ],
        ),
    ]
