# Generated by Django 2.2 on 2020-07-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0003_auto_20200719_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='query_table',
            name='REPLY',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
