# Generated by Django 2.2 on 2020-07-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_table',
            name='STSTUS',
            field=models.CharField(default='active', max_length=25),
        ),
    ]
