# Generated by Django 2.2 on 2020-07-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20200718_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_table',
            name='EMAIL',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
